# fly.toml app configuration file generated for still-bird-6972 on 2023-07-01T03:47:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-bird-6972"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
